### ISSUE TITLE
BLAST codes used at LOA

### ISSUE THREAD

**Issue by hightower8083** [ECP-WarpX/blast-communitymap#10]
### Name & Info

Igor Andriyash (hightower8083), CNRS research engineer at Laboratoire d’Optique Appliquée (LOA), user and contributor. 

- BLAST codes used: FBPIC, WARPX, HiPACE++, LASY, openPMD_viewer,  openPMD-api, Optimas
- Scientific/Engineering Domain: laser plasma science

### Location

https://www.openstreetmap.org/#map=19/48.70803/2.22153

**Comment by ax3l** [comment]
Thank you, @hightower8083! :tada:
