### ISSUE TITLE
use of WarpX at RadiaSoft

### ISSUE THREAD

**Issue by bruhwiler** [ECP-WarpX/blast-communitymap#11]
### Name & Info

name:                                         David Bruhwiler
institution:                                  RadiaSoft LLC
Blast codes used:                        WarpX
Scientific/Engineering Domain:  fusion energy

### Location

1790 38th St., Suite 306
Boulder, CO 80301

**Comment by ax3l** [comment]
Thank you, @bruhwiler! :tada:
