### ISSUE TITLE
More BLAST code use at RadiaSoft

### ISSUE THREAD

**Issue by ncook882** [ECP-WarpX/blast-communitymap#12]
*Hi, thank you for adding yourself to the BLAST community map!*

*Please provide the following information so we can add an entry:*

### Nathan Cook

*How shall we list you and the group you work in?*

name: Nathan Cook
institution: RadiaSoft LLC
Blast codes used: WarpX, Warp, IMPACT, IMPACT-T, FBPIC, OpenPMD
Scientific/Engineering Domain: particle accelerators, laser & beam plasma interactions, thermionic energy conversion

### Location

1790 38th St., Suite 306
Boulder, CO 80301

**Comment by ax3l** [comment]
Thank you, @ncook882! :tada:
