### ISSUE TITLE
use of WarpX at NIU

### ISSUE THREAD

**Issue by tanweihou** [ECP-WarpX/blast-communitymap#13]
### Name & Info

name: Wei-Hou Tan
institution: Northern Illinois University
Blast codes used: WarpX
Scientific/Engineering Domain: accelerator physics

### Location

Department of Physics
Northern Illinois University
DeKalb, IL 60115

**Comment by ax3l** [comment]
Thank you, @tanweihou! :tada:

**Comment by tanweihou** [comment]
@ax3l hey could you just update the community map with the following

Blast codes used: WarpX, ImpactX, openpmd

Thanks.
