### ISSUE TITLE
BLAST codes used at UMich

### ISSUE THREAD

**Issue by archermarx** [ECP-WarpX/blast-communitymap#14]
### Name & Info

Thomas Marks, Computational Autonomy Group at the University of Michigan

*If you like, do not hesitate to share:*

- BLAST codes used: WarpX
- Scientific/Engineering Domain: Hall thruster plasma simulation

### Location
University of Michigan, Ann Arbor, MI

**Comment by ax3l** [comment]
Thank you, @archermarx ! :tada:
