### ISSUE TITLE
BLAST Codes at UChicago Accelerator Group

### ISSUE THREAD

**Issue by electronsandstuff** [ECP-WarpX/blast-communitymap#17]
### Name & Info

Christopher Pierce, Enrico Fermi Institute, University of Chicago

- BLAST codes used: Warpx, IMPACT-T, OpenPMD
- Scientific/Engineering Domain: Scientific machine learning for particle accelerators

### Location

[Enrico Fermi Institute](https://efi.uchicago.edu/)
933 East 56th Street
South Entrance
Chicago IL 60637

**Comment by ax3l** [comment]
Thank you, @electronsandstuff ! :tada:
