### ISSUE TITLE
BLAST Codes at Lund University

### ISSUE THREAD

**Issue by AlexanderSinn** [ECP-WarpX/blast-communitymap#18]
### Name & Info

Name: Synchrotron Radiation Research
Contacts: Jonas Björklund Svensson
Organization: Lund University Department of Physics
Domain: beam-plasma, accelerators, x-ray generation
BLAST codes used: hipace++, optimas, wake-t

### Location

55.71029 13.20463

**Comment by ax3l** [comment]
Thank you, @AlexanderSinn! :tada:
