### ISSUE TITLE
University of Saskatchewan

### ISSUE THREAD

**Issue by roelof-groenewald** [ECP-WarpX/blast-communitymap#20]
### Andrei Smolyakov's group (Department of Physics and Engineering Physics)

- BLAST codes used: WarpX
- Scientific/Engineering Domain: Magnetically confined plasmas

### Location

105 Administration Pl, Saskatoon, SK S7N 5A2, Canada
https://www.openstreetmap.org/relation/13754325

**Comment by ax3l** [comment]
Thank you, @roelof-groenewald! :tada:
