### ISSUE TITLE
BLAST code usage at University of Oxford

### ISSUE THREAD

**Issue by jameschappell** [ECP-WarpX/blast-communitymap#21]
### Name & Info
- Name: James Chappell
- Group name: Laser-plasma accelerators Group, University of Oxford
- BLAST codes used: WarpX, FBPIC, HiPACE++, Wake-T, LASY, Optimas, OpenPMD
- Scientific/Engineering Domain: Laser-plasma accelerators

### Location

- Clarendon Laboratory, Department of Physics, University of Oxford, Oxford, UK

**Comment by ax3l** [comment]
Thank you, @jameschappell ! :tada: 

Wow, awesome! I did not know so many of the BLAST codes are used in your group! :star_struck:
