### ISSUE TITLE
WarpX usage - Imperial College London, UK 

### ISSUE THREAD

**Issue by cooluser26** [ECP-WarpX/blast-communitymap#22]
*Hi, thank you for adding yourself to the BLAST community map!*

*Please provide the following information so we can add an entry:*

### Name & Info

*How shall we list you and the group you work in?*

Bao Nguyen.
Affliation: Imperial College London

*Are you representing a larger organization/collaboration/project where BLAST codes are regularly used in?*

No

*If you like, do not hesitate to share:*

- BLAST codes used: WarpX
- Scientific/Engineering Domain: Accelerator Physics / beam-beam studies 

### Location

*Please provide a simple address / city or OpenStreeMap.org link for geo coordinates.*

Exhibition Road, London SW7 2AZ

*Precision does not matter, if you select your city center or laboratory this is totally fine as well.*

- go to https://www.openstreetmap.org
- select your location
- right click -> "show address"
- copy link from address bar or coordinates shown on the left

**Comment by ax3l** [comment]
Thank you @wnguyen1312, added  to the map :tada:
