### ISSUE TITLE
Add Eric to communitymap

### ISSUE THREAD

**Issue by clarkse** [ECP-WarpX/blast-communitymap#23]
*Hi, thank you for adding yourself to the BLAST community map!*

*Please provide the following information so we can add an entry:*

### Name & Info

*How shall we list you and the group you work in?*
S. Eric Clark, Helion Energy (formerly LLNL)

*Are you representing a larger organization/collaboration/project where BLAST codes are regularly used in?*

*If you like, do not hesitate to share:*

- BLAST codes used:
- WarpX/AMReX/pyAMReX
- Scientific/Engineering Domain: FRC Fusion

### Location

1415 75th St SW, Everett, WA 98203

47.93123524254789, -122.25335732871602

**Comment by ax3l** [comment]
Added - thank you, Eric! :tada:
