### ISSUE TITLE
Jeff Greason BLAST map

### ISSUE THREAD

**Issue by jgreason** [ECP-WarpX/blast-communitymap#25]
*Hi, thank you for adding yourself to the BLAST community map!*

*Please provide the following information so we can add an entry:*

Jeff Greason
Chief Technologist, Electric Sky
Chairman, Tau Zero Foundation

*How shall we list you and the group you work in?*

I'm in two relevant groups.  At Electric Sky I use an in-house modified version of FBPIC to develop propulsion systems to push against the ionosphere.  In the Tau Zero Foundation I use FBPIC to explore various interstellar plasma propulsion systems such as drag devices working against the interstellar medium.

*Are you representing a larger organization/collaboration/project where BLAST codes are regularly used in?*

No

- BLAST codes used: FBPIC
- Space Plasma Propulsion

### Location

Tucson, AZ

**Comment by ax3l** [comment]
Hi @jgreason,

Thank you for your report! Great to hear FBPIC is useful for your applications!
We would be curious what works well for you using FBPIC, and potentially the Python interface to WarpX could be useful for you as well if you need to go larger scale in the future :rocket: :sparkles:
