### ISSUE TITLE
FBPIC Users & Contributors

### ISSUE THREAD

**Issue by ax3l** [ECP-WarpX/blast-communitymap#6]
Hi @RemiLehe ,

We are starting for various reviews a map of [BLAST](https://blast.lbl.gov/codes/) users, science applications of our codes and contributors.

Do you know users and contributors of FBPIC that can be added in this? :)

**Comment by RemiLehe** [comment]
Based on recent publications (I used the institution of the first author only ; this list is not exhaustive):
- School of Mathematics and Physics, Queen’s University Belfast, UK [paper](https://www.nature.com/articles/s41598-024-56281-1)
- Shanghai Jiao Tong University, Shanghai, China [paper](https://pubs.aip.org/aip/pop/article/31/2/023109/3267711/Efficient-muon-acceleration-in-laser-wakefields)
- Department of Physics, INFN, Milan, Italy [paper](https://www.mdpi.com/2410-390X/7/4/52)
- INFN-LNF, Frascati, Italy [paper](https://www.nature.com/articles/s41598-024-52231-z)
- University of Oxford, UK [paper](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.131.245001)
- Shenzhen Technology University, Shenzhen, China [paper](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.131.145003)
- Deutsches Elektronen-Synchrotron DESY, Hamburg, Germany [most recent of many papers](https://journals.aps.org/prresearch/abstract/10.1103/PhysRevResearch.5.033205)
- University of Delhi, India [paper](https://www.cambridge.org/core/journals/journal-of-plasma-physics/article/terahertz-generation-by-a-rotating-relativistic-electron-beam-in-a-magnetized-plasma-column/FEC686E212087F0DA87549914BCDC988)
- LPGP, CNRS, Orsay, France [paper](https://doi.org/10.1063/5.0142894)
- Center for Physical Sciences and Technology, Vilnius, Lithuania [paper](https://www.cambridge.org/core/journals/journal-of-plasma-physics/article/laser-wakefield-acceleration-of-electrons-using-besselgauss-doughnut-beams-for-accelerating-beam-guiding/65070D3254B1138DED14EC892B45A0C6)
- Federal University of Health Sciences of Porto Alegre, Porto Alegre, Brasil [paper](https://doi.org/10.1063/5.0134960)
- LOA, Palaiseau, France [most recent of papers](https://www.nature.com/articles/s41566-023-01165-5)
- Weizmann Institute of Science, Rehovot, Israel [paper](https://doi.org/10.1063/5.0126293)
- Ludwig-Maximilian-Universität München, Germany [paper](https://link.aps.org/doi/10.1103/PhysRevResearch.5.013063)
- Institute of Scientific and Industrial Research, Osaka University, Osaka, Japan [paper](https://www.sciencedirect.com/science/article/pii/S0375960122005643)
- Intense Laser Irradiation Laboratory, Pisa, Italy [paper](https://www.cambridge.org/core/journals/high-power-laser-science-and-engineering/article/accurate-electron-beam-phasespace-theory-for-ionizationinjection-schemes-driven-by-laser-pulses/3EBCA963089C3544041926FE2AAA4A46)
- LLNL, USA [paper](https://doi.org/10.1063/5.0093067)
- LBNL, USA [most recent of many papers](https://doi.org/10.1063/5.0073622)
- Ulsan National Institute of Science and Technology, Ulsan, South Korea [paper](https://journals.aps.org/prab/pdf/10.1103/PhysRevAccelBeams.24.121304)
- University of Strathclyde, Glasgow, UK [paper](https://iopscience.iop.org/article/10.1088/1367-2630/ac3efd)
- Shanghai Institute of Optics and Fine Mechanics (SIOM), Shanghai, China [paper](https://www.nature.com/articles/s41586-021-03678-x)
- University of Michigan, Ann Arbor, USA [paper](https://pubs.aip.org/aip/pop/article/28/6/063104/973688/Generation-of-straight-and-curved-hollow-plasma)
- UCLA, Los Angeles, USA [paper](https://journals.aps.org/prab/pdf/10.1103/PhysRevAccelBeams.24.051302)
- University of Manchester [paper](https://doi.org/10.1088/1742-6596/1596/1/012058)

**Comment by ax3l** [comment]
Thank you, @RemiLehe :rocket: :sparkles:
