### ISSUE TITLE
Using of WarpX and openPMD-api GSI Helmholtzzentrum für Schwerionenforschung  at Darmstadt 

### ISSUE THREAD

**Issue by denisbertini** [ECP-WarpX/blast-communitymap#7]
### Name & Info
GSI Helmholtzzentrum für Schwerionenforschung  at Darmstadt Germany

- BLAST codes used: WarpX + openPMD-api
- We do basically Plasma PIC Simulation using Epoch + WarpX and use openPMD-api for
data store. 
- We also develop code based on openPMD-api 
  - Converter [EPOCH to openPMD  format](https://github.com/denisbertini/mpi-sdf2opmd/tree/main)
  - [openPMD particle reduction](https://github.com/denisbertini/opmd_reduce)
  - Parallel version of [openPMD-viewer](https://git.gsi.de/d.bertini/pp-ana) (still  in development)

### Location
GSI Helmholtzzentrum für Schwerionenforschung GmbH
Planckstraße 1
64291 Darmstadt
oder
Postfach: 11 05 52
64278 Darmstadt

**Comment by ax3l** [comment]
Thanks a lot, @denisbertini!

If you have the time, @RemiLehe @franzpoeschel and I would be super interested in your parallel openPMD-viewer efforts. We think about doing someting similar using the [openPMD-api DASK](https://openpmd-api.readthedocs.io/en/latest/analysis/dask.html) bindings. Would be super interested to learn what you have done so far! Let us coordinate :sparkles:

**Comment by denisbertini** [comment]
@ax3l  Of course!, just tell me when .
My first prototype for an parallel openPMD-viewer is just ready now. 
We can discuss the details together.
