### ISSUE TITLE
BLAST community map contribution

### ISSUE THREAD

**Issue by berceanu** [ECP-WarpX/blast-communitymap#9]
*Hi, thank you for adding yourself to the BLAST community map!*

*Please provide the following information so we can add an entry:*

### Name & Info

*How shall we list you and the group you work in?*
Andrei Berceanu, ELI-NP

*Are you representing a larger organization/collaboration/project where BLAST codes are regularly used in?*

*If you like, do not hesitate to share:*

- BLAST codes used: WarpX, fbpic, Wake-T, openPMD-api, LASY, Optimas
- Scientific/Engineering Domain: High-power laser-plasma interaction

### Location

*Please provide a simple address / city or OpenStreeMap.org link for geo coordinates.*
*Precision does not matter, if you select your city center or laboratory this is totally fine as well.*

- go to https://www.openstreetmap.org
- select your location
- right click -> "show address"
- copy link from address bar or coordinates shown on the left

https://www.openstreetmap.org/#map=18/44.34983/26.05043

**Comment by ax3l** [comment]
Thank you, @berceanu! :tada: 

Please feel free to also add to the codes you contribute/develop in BLAST. See the commit below.
